### ISSUE TITLE
修饰classless样式

### ISSUE THREAD

**Issue by RebelPotato** [wyast/wyast.github.io#13]
> 3. nav的ul换成两行、图片变为两行、aside消失是此css规定的行为。可以修改。
>  到时候要把ul换成html5规定的menu元素，aside弄大一点，在页面较窄的时候并到文章中……要改的东西还多着呢。

按照 https://github.com/wyast/wyast.github.io/issues/9#issuecomment-1938534042 的想法修改。

**Comment by RebelPotato** [comment]
已完成：
1. 更换ul元素为menu
2. 改变两边的大小
3. 增加“一长条”图片样式

**Comment by RebelPotato** [comment]
已完成：
1. 加入一个简单的目录，会在滑动到对应部分时高亮
2. 再改变两边大小

现在目录很丑。不知道怎样的目录比较好看？ @An-314 @liuyifan22 
https://github.com/wyast/wyast.github.io/commit/eedd996c9ae670a607beb13e9db9b410d93c47bc

https://css-tricks.com/parsing-markdown-into-an-automated-table-of-contents/ 可能值得参考。

**Comment by liuyifan22** [comment]
是在classless-update分支吗？我拉下来咋没看到侧边目录/facepalm

另，我这儿显示index正文塌陷到左边了，你们那儿有问题吗？

**Comment by RebelPotato** [comment]
现在只有guide.html增加了新的样式。另外恭喜，塌陷是feature！

**Comment by liuyifan22** [comment]
看到了新的侧边目录，支持鼠标划过时的互动，支持上下滚动页面时的合理动作，非常赞！感觉功能上已经完备了，目前想到几个trivial的外观改进方法：
1. 配置更加好看的文字与高亮块颜色组合：比如提高高亮块的透明度。但是这里的art可能很有讲究，实在不行抓个宣传部的人来辅助。
2. 高亮逻辑：目前逻辑是“高亮所有的页面上显示的标题”，似乎与人们习惯的“高亮页面上最上部的标题”不符
3. 增大标题栏的宽度：我目前在笔记本edge上看到“更多信息”被分为了两行，如果把目录宽度增加会好看
4. 抄大厂作业：据我调查，csdn的目录简明美观（与我们不同的仅是配色），知乎的侧边栏目录花哨美观（例：https://www.zhihu.com/question/597728323）

非常好的侧边栏目录！建议是merge到main中，并且删除anchor分支，我们从这个继续开发。

另，塌陷feature到底是什么鬼？

**Comment by liuyifan22** [comment]
把classless-update中Latex的一张图换了，其他功能已经检查，并无更改。已经提交pr，请检查

**Comment by RebelPotato** [comment]
存档。

这是CSDN的目录。
![image](https://github.com/wyast/wyast.github.io/assets/64510405/d40af2b3-6bc5-4183-9b9a-0456e54584eb)

这是知乎的目录。
![image](https://github.com/wyast/wyast.github.io/assets/64510405/1c87c52e-1c1c-474b-8698-0d7804521a1f)

**Comment by An-314** [comment]
抱歉，最近在陪老人和给导师干活，跟进得不是很勤。

感觉现在这样的目录达到了我们预期的效果。

我在以下的方面做了一点改进`da67cad`：

1. 正如@liuyifan22 所说，高亮逻辑可以修改一下，我修改了：将最新浏览到的标签加粗
2. 高亮块具体的样式也进行了一些修改，稍微留了些间距，增加了一些动态的感觉

抱歉我的格式化工具把原来的格式搞的不统一了，求教一下你们都用的什么格式化工具。

想知道什么导致的塌陷，发现无论是index和guide都向左有一些塌陷。感觉找到了原因可能对修复：
> 增大标题栏的宽度：我目前在笔记本edge上看到“更多信息”被分为了两行，如果把目录宽度增加会好看

会有帮助。

**Comment by An-314** [comment]
感觉还有一点可以改进是将
![image](https://github.com/wyast/wyast.github.io/assets/129043126/b18ae421-5ab1-42fe-8cb2-ed5d50703d95)
这里也调整出来间距，因为剩下的都是有间距的，但是这两个高亮块连着可能也会导致不是很美观

或者高亮块之间都没有间距也许也可以(?

**Comment by RebelPotato** [comment]
> 抱歉我的格式化工具把原来的格式搞的不统一了，求教一下你们都用的什么格式化工具。

没有使用自带的格式化工具，classless.de基础样式本身比较压缩。得自己手动把样式表改回来。我自己来吧。
@An-314 确认一下，你样式表里是不是仅修改了这一部分？
![image](https://github.com/wyast/wyast.github.io/assets/64510405/7908e2a8-18cb-476c-9689-066c802b996a)

> 想知道什么导致的塌陷，发现无论是index和guide都向左有一些塌陷。感觉找到了原因可能对修复：

见 #16 。

之前提到的一些样式建议都非常好。到时候分成一个一个feature一点点加，现在就不做大修改了。
（突然手有点痒，选其中容易的加吧。）

**Comment by An-314** [comment]
> 你样式表里是不是仅修改了这一部分？

是这样的。

> 得自己手动把样式表改回来。我自己来吧。

十分抱歉，后面我把自动格式化工具关掉。
