### ISSUE TITLE
锚点用法（详见anchor-LaTeX）

### ISSUE THREAD

**Issue by liuyifan22** [wyast/wyast.github.io#14]
在LaTeX页眉的导航栏中加入了锚点，点击锚点可以跳转到对应板块。

但是存在问题，因为页眉的存在，跳转后锚点锚定位置被遮挡。例如设置锚点在H2处，跳转过去，H2被页眉遮挡。故我现在唯象地把锚点设置在了希望跳转之位置的两行之上，效果不错，但非长远之计。

我的建议：
1 考虑黄神说的，侧边浮动目录。
2 想办法设置页面范围为页眉以下。目前的页眉应该是漂浮在页面的上部。

诸位怎么看？

**Comment by An-314** [comment]
1. 我是觉得侧边浮动目录是更合理的方法，看到很多博客都是这么搞的

2. 我觉得上面的导航栏可以考虑指向一些二级页面，比如说blog，doc，info的目录等等。（好像Jekyll对这个的管理也是方便的）

    目前考虑的Jekyll方案可以为页面分类（例如：blog、info、default...），然后给每一类定制一种css。对于同一种CSS我们可能可以考虑使用同样的导航栏，在生成网页时，Jekyll会自动把这个导航头加进去。这样在写文本时就可以完全写md，而不用在意html的任何内容了。

**Comment by RebelPotato** [comment]
同意 @An-314 对页面排版的看法。锚点也可以加，我加了一个新commit https://github.com/wyast/wyast.github.io/commit/ca98c774b4ee0bafd28464f8bc0143276872ca8f ，现在可以将anchor放在标题的同一行。

**Comment by liuyifan22** [comment]
抱歉消失了一天。感谢Mr Potato 加的anchor类和smooth方法，感觉可以沿用到侧边目录方案。Jekyll我也将去学习了，届时若有不会的再来请教二位。
