### ISSUE TITLE
避免样式文件过于臃肿

### ISSUE THREAD

**Issue by RebelPotato** [wyast/wyast.github.io#6]
style.css文件暂时没有问题，但目前不同文章缺乏统一的样式，随着文章的增多，样式文件可能会变得臃肿。

可能的应对策略：
* 创建一份style guide，后续写作的html文章尽量按此风格创作 （#7）
* 使用类似Sass的工具生成css文件（待定）

**Comment by RebelPotato** [comment]
这可能是一个伪问题，等到css超过1000行之类的再考虑？

**Comment by liuyifan22** [comment]
Great insight! We may see to it right now, or it'll be tricky when the fat css really appears/smirk

**Comment by RebelPotato** [comment]
那就以后再说。
